sudo: required
language: minimal

git:
  depth: 2

branches:
  only:
  - master
  - devel

services:
  - docker

env:
  global:
    - IMAGE_REPO=gcr.io/dd-decaf-cfbf6/design-storage
    - IMAGE_TAG=${TRAVIS_BRANCH}

install:
  - docker build -t ${IMAGE_REPO}:${TRAVIS_COMMIT::12} -t ${IMAGE_REPO}:${TRAVIS_BRANCH} .
  - make setup

script:
  - make flake8
  - make isort
  - make license
  - make safety
  - make test-travis

before_deploy:
  - ./scripts/install_gcloud.sh
  - ./scripts/install_kubectl.sh
  - docker push ${IMAGE_REPO}:${TRAVIS_COMMIT::12}
  - docker push ${IMAGE_REPO}:${TRAVIS_BRANCH}

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true

notifications:
  email: false
  slack:
    rooms:
      - secure: "KQBS9AM/sfVa9W6NeuVae38rbLD2fJBT+g+kueJl0C9XQUbwR2Win84AJbfZJWYdlJJC3yIVaFHZRrDGadtI8r8mt7rSXZPboZpedHFuNXPMrKIJtW5Ve2rlnuuIHzzAGDEzl5L0e6aY6QUuUTJY6ux/HwTmP9vMxhP8w3m1ki34/kYi3nyAUZVQMmJ32hSmGBRjrPVIFnRZGlVHl1oDd2iXva8W8SFU2vg44GuXYSDHFZw6SMfgiRPeVvmKz+MizZvLcHsGh75Ie0a9cp4oEm3dZ5H5d2tPjRf2meplH6Sd9OiKS8VUnO448eaPSDilMFa85LOogIs+mjk521OSok+hEOmhJ94dI/b/STNWAe7FG3LdNB0AGHSNM6GBAN0AvngZgV1GhdjqQm06ii/Oiqw8fJBwBOWqArz3I2ZoVP9klP15FHYm1/tQOrkdMfzDw07eQqVIp0IzQOchFLo7IUwduCXXswayoMd+ClV1UZpijDQTf2IVAbenTK3yM5jxdsE5zejYlim1IEOnzULwCuQ7NnSEy1gJ4+aFg5/BzeG2gshDCISO9ZAIgwfC9UAqOU61X+Rt1FKcF+Xeyg/INVZAHTHhytxPuv29IL1zgWt8VaJI0Btsv55UuffzW5gYC2TVwX4Dw0H+GyW87ms1nKsQ/GK/fBlzQwO5Rz8l6qY="
