"""empty message

Revision ID: 6ca67d1ca29a
Revises: 7ca65b6611b6
Create Date: 2019-01-08 13:16:17.156308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca67d1ca29a'
down_revision = '7ca65b6611b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design', sa.Column('method', sa.String(), nullable=False, server_default='Manual'))
    op.alter_column('design', 'method', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design', 'method')
    # ### end Alembic commands ###
